# Changes here will be overwritten by Copier
_commit: v2.0.2
_src_path: gh:lincc-frameworks/python-project-template
author_email: samschmidt@ucdavis.edu
author_name: Samuel Schmidt
create_example_module: false
custom_install: true
enforce_style: []
failure_notification: []
include_benchmarks: false
include_docs: false
mypy_type_checking: none
package_name: desc_bpz
project_license: MIT
project_name: desc-bpz
project_organization: LSSTDESC
python_versions:
- '3.9'
- '3.10'
- '3.11'
